"""Home Assistant-independent async GWM cloud client foundation."""

from .anz_auth import (
    AnzAuthenticated,
    AnzAuthenticationResult,
    AnzAuthState,
    AnzCredentials,
    AnzSessionReclaimRequired,
    AnzVerificationRequired,
)
from .china_client import (
    ChinaAuthenticated,
    ChinaAuthenticationResult,
    ChinaAuthState,
    ChinaClient,
    ChinaClientConfig,
    ChinaCredentials,
    ChinaInitializationRequired,
    ChinaRiskControlRequired,
    ChinaVehicle,
    ChinaVehicleStatus,
    ChinaVerificationRequired,
)
from .client import GwmClient
from .config import GwmClientConfig, RequestTimeouts
from .crypto import (
    GeneratedClientCertificateRequest,
    generate_client_certificate_request,
    load_certificate,
    recover_transformed_private_key,
)
from .errors import (
    GwmApiError,
    GwmAuthenticationError,
    GwmClientError,
    GwmClosedError,
    GwmConfigurationError,
    GwmDeadlineExceededError,
    GwmHttpError,
    GwmNetworkError,
    GwmOptionalEndpointError,
    GwmProtocolError,
    GwmRateLimitError,
    GwmRedirectError,
    GwmResponseTooLargeError,
    GwmRoutePolicyError,
    GwmSchemaError,
    GwmTlsError,
    GwmTransportError,
)
from .eu_auth import (
    EuAuthenticated,
    EuAuthenticationResult,
    EuAuthState,
    EuCredentials,
    EuVerificationRequired,
)
from .eu_identity import (
    EuBootstrapMaterial,
    EuIdentityError,
    EuIssuedIdentity,
    create_eu_bootstrap_ssl_context,
    create_eu_issued_ssl_context,
    is_eu_issued_identity_usable,
)
from .models import (
    CloudClimateConfiguration,
    CloudStatusItem,
    CloudVehicle,
    CloudVehicleBasics,
    CloudVehicleStatus,
    GwmSession,
    VehicleIdentifier,
)
from .regions import Region
from .signing import (
    ANZ_BT_AUTH,
    EU_BT_AUTH,
    EU_GWM_AUTH,
    RUSSIA_GWM_AUTH,
    SignedRequest,
    SigningProfile,
    sign_request,
)
from .tls import LEGACY_CIPHER_STRING, create_gwm_ssl_context

__all__ = [
    "ANZ_BT_AUTH",
    "AnzAuthenticated",
    "AnzAuthenticationResult",
    "AnzAuthState",
    "AnzCredentials",
    "AnzSessionReclaimRequired",
    "AnzVerificationRequired",
    "CloudClimateConfiguration",
    "CloudStatusItem",
    "CloudVehicle",
    "CloudVehicleBasics",
    "CloudVehicleStatus",
    "ChinaAuthenticated",
    "ChinaAuthenticationResult",
    "ChinaAuthState",
    "ChinaClient",
    "ChinaClientConfig",
    "ChinaCredentials",
    "ChinaInitializationRequired",
    "ChinaRiskControlRequired",
    "ChinaVehicle",
    "ChinaVehicleStatus",
    "ChinaVerificationRequired",
    "EU_BT_AUTH",
    "EU_GWM_AUTH",
    "EuAuthenticated",
    "EuAuthenticationResult",
    "EuAuthState",
    "EuBootstrapMaterial",
    "EuCredentials",
    "EuIdentityError",
    "EuIssuedIdentity",
    "EuVerificationRequired",
    "GwmApiError",
    "GwmAuthenticationError",
    "GwmClient",
    "GwmClientConfig",
    "GwmClientError",
    "GwmClosedError",
    "GwmConfigurationError",
    "GwmDeadlineExceededError",
    "GwmHttpError",
    "GwmNetworkError",
    "GwmOptionalEndpointError",
    "GwmProtocolError",
    "GwmRateLimitError",
    "GwmRedirectError",
    "GwmResponseTooLargeError",
    "GwmRoutePolicyError",
    "GwmSchemaError",
    "GwmSession",
    "GwmTlsError",
    "GwmTransportError",
    "LEGACY_CIPHER_STRING",
    "RUSSIA_GWM_AUTH",
    "Region",
    "RequestTimeouts",
    "GeneratedClientCertificateRequest",
    "SignedRequest",
    "SigningProfile",
    "VehicleIdentifier",
    "create_gwm_ssl_context",
    "create_eu_bootstrap_ssl_context",
    "create_eu_issued_ssl_context",
    "generate_client_certificate_request",
    "load_certificate",
    "is_eu_issued_identity_usable",
    "recover_transformed_private_key",
    "sign_request",
]
